### ISSUE TITLE
Deploying  github pages failed.

### ISSUE THREAD

**Issue by Alex313031** [jxl-community/jxl-community.github.io#9]
@jonsneyers Was looking at the site today, and noticed neither mine nor @yota-code commits are actually live on the https://jpegxl.info/ site. 

Looks like the latest two page deployments (made in the last two weeks and triggered by our commits) failed:

https://github.com/jxl-community/jxl-community.github.io/actions/runs/4304089171
https://github.com/jxl-community/jxl-community.github.io/actions/runs/4304165005

**Comment by jonsneyers** [comment]
Strange, must be some GitHub internal problem or something. Seems to work again now.

**Comment by Alex313031** [comment]
@jonsneyers Nice. and thanks for approving my commit. I made a separate thumbnail for the test site so that it could be deployed on its own. I put it on my site here > https://thorium.rocks/misc/jxl-test-page/
